[workspace]
members = [
    "eclssd",
    "lib/*",
]

[workspace.dependencies]
anyhow = "1.0"
clap = "4.0"
eclss = { path = "lib/eclss" }
embedded-hal = { version = "1" }
embedded-hal-async = { version = "1" }
maitake-sync = "0.1.1"
tokio = "1.37"
tinymetrics = { git = "https://github.com/hawkw/tinymetrics"}
tracing =  "0.1.40"
tracing-subscriber = "0.3.18"
linux-embedded-hal = "0.4.0"
serde = "1.0"
pmsa003i = { path = "lib/pmsa003i" }

[patch.crates-io]
linux-embedded-hal = { git = "https://github.com/rust-embedded/linux-embedded-hal/" }
