[package]
name = "eclssd"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
eclss = { workspace = true, features = ["pmsa003i", "tracing", "serde"] }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
linux-embedded-hal = { workspace = true, features = ["i2c", "async-tokio"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
